import os
import torch
import numpy as np
import glob
import warnings

# ==========================================
# SILENCE THIRD-PARTY WARNINGS
# ==========================================
warnings.filterwarnings("ignore", category=UserWarning)
warnings.filterwarnings("ignore", category=FutureWarning)
warnings.filterwarnings("ignore", message=".*ChainedAssignmentError.*") 
warnings.filterwarnings("ignore", module="recbole.*")

# --- NUMPY 1.24+ HOTFIX FOR RECBOLE ---
np.float = float
np.int = int
np.bool = bool
np.object = object
# --------------------------------------

# --- PYTORCH 2.6 HOTFIX FOR RECBOLE ---
_original_load = torch.load
def _patched_load(*args, **kwargs):
    kwargs['weights_only'] = False
    return _original_load(*args, **kwargs)
torch.load = _patched_load
# --------------------------------------

from recbole.quick_start import run_recbole, load_data_and_model
from recbole.utils import get_trainer

from src.modifiers import apply_knn, apply_contrastive_mapper, apply_graph_grafting, apply_tfidf_knn
from src.visualization import generate_visual_plot, plot_knn_sweep

class ColdStartExperiment:
    def __init__(self, dataset_name, model_name='LightGCN', is_oracle=False, seed=2024):
        self.dataset_name = dataset_name
        self.model_name = model_name
        self.is_oracle = is_oracle
        self.seed = seed
        self.saved_model_path = None 

    def prepare_base_model(self):
        suffix = "oracle" if self.is_oracle else "strict"
        expected_filename = f"{self.model_name}_{self.dataset_name}_seed{self.seed}_{suffix}.pth"
        expected_path = os.path.join('saved', expected_filename)
        
        if os.path.exists(expected_path):
            print(f"\n♻️  Found cached model: {expected_filename}")
            print(f"    Skipping training and loading directly from disk!")
            self.saved_model_path = expected_path
            return
            
        mode_text = "ORACLE (Global Random Mix)" if self.is_oracle else "STRICT HOLDOUT (Targeted Item Split)"
        print(f"\n{'='*70}")
        print(f" TRAINING BASE MODEL: {self.model_name} | {self.dataset_name} | Seed: {self.seed} [{mode_text}] ")
        print(f"{'='*70}")
        
        if self.is_oracle:
            # Oracle uses the master .inter file and randomly splits interactions
            config_dict = {
                'seed': self.seed,
                'state': 'WARNING',       
                'show_progress': True,   
                'eval_args': {'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'mode': 'full'}
            }
        else:
            # Strict models load the physically split Targeted Holdout files generated by generate_holdout.py
            config_dict = {
                'seed': self.seed,
                'state': 'WARNING',       
                'show_progress': True,   
                'benchmark_filename': ['train', 'valid', 'test'], 
                'eval_args': {'mode': 'full'}, 
                'load_col': {'inter': ['user_id', 'item_id', 'timestamp']}
            }
        
        run_recbole(
            model=self.model_name, 
            dataset=self.dataset_name, 
            config_file_list=['configs/base_recbole.yaml'], 
            config_dict=config_dict
        )
        
        checkpoints = glob.glob(os.path.join('saved', f'{self.model_name}-*.pth'))
        newest_model = max(checkpoints, key=os.path.getmtime)
        
        os.rename(newest_model, expected_path)
        self.saved_model_path = expected_path
        
        print(f"✅ Base model trained and cached to disk at: {self.saved_model_path}")

    def run_evaluation(self, modifier_func=None, name="Baseline"):
        if self.saved_model_path is None:
            self.prepare_base_model()

        print(f"\n--- Running Evaluation: {name} ---")
        config, model, dataset, train_data, valid_data, test_data = load_data_and_model(
            model_file=self.saved_model_path
        )
        
        current_state = {
            'config': config,
            'model': model,
            'dataset': dataset,
            'train_data': train_data,
            'test_data': test_data
        }
        
        if modifier_func:
            current_state = modifier_func(current_state)
            
        print("Evaluating model on test set...")
        model = current_state['model']
        test_data = current_state['test_data']
        
        trainer = get_trainer(config['MODEL_TYPE'], config['model'])(config, model)
        test_result = trainer.evaluate(test_data, load_best_model=False, show_progress=False)
        return test_result

def run_knn_suite(dataset_name='amazon-office', seeds=[42]):
    k_values = [1, 3, 5, 8, 10, 15, 20]
    sweep_hit = []
    sweep_ndcg = []

    print(f"\n--- Starting KNN Sweep for {dataset_name} ---")

    for k in k_values:
        std_exp = ColdStartExperiment(dataset_name, model_name='LightGCN', is_oracle=False, seed=42)
        std_exp.prepare_base_model()
        
        knn_mod = lambda state: apply_knn(state, k_neighbors=k, strategy_name="vibe_only")
        res = std_exp.run_evaluation(modifier_func=knn_mod, name=f"1-NN (K={k})")
        
        sweep_hit.append(res['hit@10'])
        sweep_ndcg.append(res['ndcg@10'])
        
    plot_knn_sweep(
        k_values=k_values, 
        hit_scores=sweep_hit, 
        ndcg_scores=sweep_ndcg, 
        title=f"KNN Neighbor Sweep: {dataset_name.upper()}",
        filename=f"knn_sweep_{dataset_name}.png"
    )

def run_statistical_suite(dataset_name='ml-100k', seeds=None):
    if seeds is None:
        seeds = [42, 101, 777, 2024, 9999]
        
    print(f"\n{'='*80}")
    print(f" STARTING LIGHTGCN MASTER STATISTICAL SUITE: {dataset_name.upper()}")
    print(f" Seeds to evaluate: {seeds}")
    print(f"{'='*80}")

    architectures = [
        "lgcn_oracle",
        "lgcn_baseline",          
        "lgcn_tf_idf_raw",
        "lgcn_tf_idf_vibe_only",
        "lgcn_tf_idf_combination",
        "lgcn_mapper_net",
        "lgcn_1-nn_raw",
        "lgcn_1-nn_vibe_only",
        "lgcn_1-nn_combination",  
        "lgcn_graft_raw",
        "lgcn_graft_vibe_only",
        "lgcn_graft_combination"
    ]
    
    # Expanded dictionaries to hold 10, 20, 50 metrics natively calculated by RecBole
    results = {arch: {
        'hit@10': [], 'hit@20': [], 'hit@50': [], 'ndcg@10': []
    } for arch in architectures}

    for idx, seed in enumerate(seeds):
        print(f"\n\n{'#'*60}")
        print(f" RUNNING ACADEMIC SUITE {idx+1}/{len(seeds)} (SEED: {seed})")
        print(f"{'#'*60}")
        
        # 1. ORACLE CEILING
        oracle_exp = ColdStartExperiment(dataset_name, model_name='LightGCN', is_oracle=True, seed=seed)
        oracle_exp.prepare_base_model()
        orc_res = oracle_exp.run_evaluation(name="LightGCN Oracle Baseline")
        results["lgcn_oracle"]['hit@10'].append(orc_res.get('hit@10', 0.0))
        results["lgcn_oracle"]['hit@20'].append(orc_res.get('hit@20', 0.0))
        results["lgcn_oracle"]['hit@50'].append(orc_res.get('hit@50', 0.0))
        results["lgcn_oracle"]['ndcg@10'].append(orc_res.get('ndcg@10', 0.0))

        # 2. STANDARD MODELS
        std_exp = ColdStartExperiment(dataset_name, model_name='LightGCN', is_oracle=False, seed=seed)
        std_exp.prepare_base_model()
        
        # A. STRICT BASELINE
        base_res = std_exp.run_evaluation(modifier_func=None, name="Strict Baseline")
        results["lgcn_baseline"]['hit@10'].append(base_res.get('hit@10', 0.0))
        results["lgcn_baseline"]['hit@20'].append(base_res.get('hit@20', 0.0))
        results["lgcn_baseline"]['hit@50'].append(base_res.get('hit@50', 0.0))
        results["lgcn_baseline"]['ndcg@10'].append(base_res.get('ndcg@10', 0.0))
        
        # B. TF-IDF LEXICAL BASELINE
        for strategy in ["raw", "vibe_only", "combination"]:
            display_name = "LLM Enhanced" if strategy == "vibe_only" else strategy.title()
            tfidf_mod = lambda state, s=strategy: apply_tfidf_knn(state, k_neighbors=1, strategy_name=s)
            res = std_exp.run_evaluation(modifier_func=tfidf_mod, name=f"TF-IDF ({display_name})")
            results[f"lgcn_tf_idf_{strategy}"]['hit@10'].append(res.get('hit@10', 0.0))
            results[f"lgcn_tf_idf_{strategy}"]['hit@20'].append(res.get('hit@20', 0.0))
            results[f"lgcn_tf_idf_{strategy}"]['hit@50'].append(res.get('hit@50', 0.0))
            results[f"lgcn_tf_idf_{strategy}"]['ndcg@10'].append(res.get('ndcg@10', 0.0))
        
        # C. Mapper Network
        map_mod = lambda state: apply_contrastive_mapper(state, strategy_name="raw", epochs=150)
        res = std_exp.run_evaluation(modifier_func=map_mod, name="Mapper Network (Raw)")
        results["lgcn_mapper_net"]['hit@10'].append(res.get('hit@10', 0.0))
        results["lgcn_mapper_net"]['hit@20'].append(res.get('hit@20', 0.0))
        results["lgcn_mapper_net"]['hit@50'].append(res.get('hit@50', 0.0))
        results["lgcn_mapper_net"]['ndcg@10'].append(res.get('ndcg@10', 0.0))

        # D. 1-NN Weight Copy
        for strategy in ["raw", "vibe_only", "combination"]:
            display_name = "LLM Enhanced" if strategy == "vibe_only" else strategy.title()
            knn_mod = lambda state, s=strategy: apply_knn(state, k_neighbors=1, strategy_name=s)
            res = std_exp.run_evaluation(modifier_func=knn_mod, name=f"1-NN Weight Copy ({display_name})")
            results[f"lgcn_1-nn_{strategy}"]['hit@10'].append(res.get('hit@10', 0.0))
            results[f"lgcn_1-nn_{strategy}"]['hit@20'].append(res.get('hit@20', 0.0))
            results[f"lgcn_1-nn_{strategy}"]['hit@50'].append(res.get('hit@50', 0.0))
            results[f"lgcn_1-nn_{strategy}"]['ndcg@10'].append(res.get('ndcg@10', 0.0))

        # E. Graph Grafting
        for strategy in ["raw", "vibe_only", "combination"]:
            display_name = "LLM Enhanced" if strategy == "vibe_only" else strategy.title()
            graft_mod = lambda state, s=strategy: apply_graph_grafting(state, strategy_name=s)
            res = std_exp.run_evaluation(modifier_func=graft_mod, name=f"Graph Grafting ({display_name})")
            results[f"lgcn_graft_{strategy}"]['hit@10'].append(res.get('hit@10', 0.0))
            results[f"lgcn_graft_{strategy}"]['hit@20'].append(res.get('hit@20', 0.0))
            results[f"lgcn_graft_{strategy}"]['hit@50'].append(res.get('hit@50', 0.0))
            results[f"lgcn_graft_{strategy}"]['ndcg@10'].append(res.get('ndcg@10', 0.0))

    def calc_stats(arr):
        if len(arr) == 0: return 0.0, 0.0
        return np.mean(arr), np.std(arr)

    print("\n" + "="*165)
    print(f" 🏆 ULTIMATE LIGHTGCN {len(seeds)}-SEED STATISTICAL SCORECARD 🏆")
    print("="*165)
    print(f"{'Model Architecture':<38} | {'Hit@10':<18} | {'Hit@20':<18} | {'Hit@50':<18} | {'NDCG@10':<18} | {'Method'}")
    print("-" * 165)
    
    def print_row(key, name_override, note):
        h10_m, h10_s = calc_stats(results[key]['hit@10'])
        h20_m, h20_s = calc_stats(results[key]['hit@20'])
        h50_m, h50_s = calc_stats(results[key]['hit@50'])
        n10_m, n10_s = calc_stats(results[key]['ndcg@10'])
        print(f"{name_override:<38} | {h10_m:.4f} ± {h10_s:.4f} | {h20_m:.4f} ± {h20_s:.4f} | {h50_m:.4f} ± {h50_s:.4f} | {n10_m:.4f} ± {n10_s:.4f} | {note}")

    print_row("lgcn_baseline", "LightGCN Baseline", "No Imputation (Strict Cold)")
    print("-" * 165)
    print_row("lgcn_tf_idf_raw", "LightGCN + TF-IDF (Raw)", "Lexical Copy (K=1)")
    print_row("lgcn_tf_idf_vibe_only", "LightGCN + TF-IDF (LLM Enhanced)", "Lexical Copy (K=1)")
    print_row("lgcn_tf_idf_combination", "LightGCN + TF-IDF (Combo)", "Lexical Copy (K=1)")
    print("-" * 165)
    print_row("lgcn_mapper_net", "LightGCN + Neural Mapper", "Weight Imputation")
    print("-" * 165)
    print_row("lgcn_1-nn_raw", "LightGCN + 1-NN (Raw)", "Weight Copy")
    print_row("lgcn_1-nn_vibe_only", "LightGCN + 1-NN (LLM Enhanced)", "Weight Copy")
    print_row("lgcn_1-nn_combination", "LightGCN + 1-NN (Combo)", "Weight Copy")
    print("-" * 165)
    print_row("lgcn_graft_raw", "LightGCN + Grafting (Raw)", "Edge Injection")
    print_row("lgcn_graft_vibe_only", "LightGCN + Grafting (LLM Enhanced)", "Edge Injection (Proposed)")
    print_row("lgcn_graft_combination", "LightGCN + Grafting (Combo)", "Edge Injection (Proposed)")
    print("-" * 165)
    print_row("lgcn_oracle", "LightGCN Oracle", "Theoretical Maximum")
    print("="*165)
    
    generate_visual_plot(results, dataset_name, len(seeds))

if __name__ == "__main__":
    
    datasets_to_run = [
        "amazon-office",
        "amazon-digital-music"
    ]
    
    for dataset in datasets_to_run:
        run_statistical_suite(dataset)
        run_knn_suite(dataset_name=dataset)