# scripts/extract_text.py
import pandas as pd
import os
import json

# Define which columns contain the semantic text for each dataset
DATASET_TEXT_COLUMNS = {
    'amazon-office': ['title:token_seq', 'brand:token', 'categories:token_seq', 'description:token_seq'],
    'amazon-digital-music': ['title:token_seq', 'brand:token', 'categories:token_seq', 'description:token_seq'],
    'ml-1m': ['movie_title:token_seq', 'class:token_seq'], # MovieLens (Sparse)
    'ml-100k': ['movie_title:token_seq', 'class:token_seq'], # MovieLens 100k (Sparse)
    'steam': ['app_name:token_seq', 'genres:token_seq', 'tags:token_seq', 'reviews:token_seq'] # Steam (Rich)
}

def extract_text(dataset_name):
    print(f"Extracting text for {dataset_name}...")
    
    SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
    ROOT_DIR = os.path.dirname(SCRIPT_DIR)
    item_path = os.path.join(ROOT_DIR, 'dataset', dataset_name, f'{dataset_name}.item')
    save_path = os.path.join(ROOT_DIR, 'dataset', dataset_name, 'item_to_text.json')

    if not os.path.exists(item_path):
        raise FileNotFoundError(f"❌ FATAL: {item_path} not found. Did you run setup_{dataset_name}.py first?")

    # Read the dense .item file generated by split_data.py
    df = pd.read_csv(item_path, sep='\t', dtype=str)
    item_col = [col for col in df.columns if 'item_id' in col][0]
    
    target_cols = DATASET_TEXT_COLUMNS.get(dataset_name, [])
    item_dict = {}

    for _, row in df.iterrows():
        item_id = str(row[item_col])
        text_parts = []
        
        for col in target_cols:
            if col in df.columns and pd.notna(row[col]):
                # Clean up RecBole underscores for the LLM
                clean_text = str(row[col]).replace('_', ' ')
                text_parts.append(f"{col.split(':')[0].capitalize()}: {clean_text}")
                
        combined_text = " | ".join(text_parts).strip()
        if not combined_text:
            combined_text = "No description available."
            
        item_dict[item_id] = combined_text

    with open(save_path, 'w', encoding='utf-8') as f:
        json.dump(item_dict, f, indent=4)
        
    print(f"✅ Extracted {len(item_dict)} items to item_to_text.json")

if __name__ == "__main__":
    for ds in DATASET_TEXT_COLUMNS.keys():
        extract_text(ds)